name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          $FOO = "Fighters"
          echo "::set-env name=FOO_STATE::$FOO"

      - name: Run a multi-line script
        run: |
          echo "The Foo are ${{ env.FOO_STATE }}" 
